# Basic
name:               "ethereal.io"

author:
  twitter:          punnie
  github:           punnie

copyright:
  year:             2018
  name:             Pedro Coelho

# Google-analytics
google-analytics:
  id:               "UA-100884848-1"

# Disqus
disqus:
  id:               "ethereal-io"

# URL
url:                "https://ethereal.io"
baseurl:            ""

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           UTC
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           10
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about/"
  - name:           "Archive"
    url:            "/archive/"
  - name:           "Tags"
    url:            "/tags/"
  - name:           "Github"
    url:            "https://github.com/punnie"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

plugins:
  - jekyll-seo-tag
  - jekyll-paginate

exclude:
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - Rakefile
  - vendor
