---
version: 2
jobs:
  build:
    docker:
      - image: ruby:2.4

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Build site
          command: bundle exec jekyll build
      - run:
          name: HTML proof generated site
          command: bundle exec htmlproofer ./_site --allow-hash-href --check-html --disable-external
      - persist_to_workspace:
          root: .
          paths:
            - .site

    environment:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true


  deploy:
    docker:
      - image: garland/aws-cli-docker:1.16.140

    steps:
      - attach_workspace:
          at: .site
      - run:
          name: Sync to S3 bucket
          command: aws s3 sync ./_site/ s3://ethereal.io/ --delete

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy
