---
version: 2.1

jobs:
  build:
    docker:
      - image: ruby:2.6

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: gem update bundler && bundle install
      - run:
          name: Build site
          command: bundle exec jekyll build
      - run:
          name: HTML proof generated site
          command: bundle exec htmlproofer ./_site --allow-hash-href --check-html --disable-external
      - persist_to_workspace:
          root: .
          paths:
            - .site

    environment:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true

workflows:
  version: 2
  build:
    jobs:
      - build
